---
title: "Cladocopium C1 DEG - DualT - Functional Analyses - 18.11.2020"
author: "Julie Lê-Hoang"
---

# 1. Load data and packages

## 1.1. Load Packages

```{r}
#install.packages("ggplot2")
library("ggplot2")
#install.packages("stringr", dependencies = TRUE)
library("stringr")
#install.packages("RColorBrewer")
library("RColorBrewer")
#install.packages("dplyr")
library("dplyr")
#install.packages("reshape2")
library("reshape2")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("FactoMineR")
library("FactoMineR")
#install.packages("pheatmap")
library("pheatmap")
library("htmlwidgets")
library("stringi")
## try http:// if https:// URLs are not supported
#source("http://bioconductor.org/biocLite.R")
#biocLite("DESeq2")
library("DESeq2")
#biocLite("edgeR")
library("edgeR")
#biocLite("limma")
library("limma")
#install.packages("gplots")
library("gplots")
#install.packages("venneuler")
library("venneuler")
#install.packages("VennDiagram")
library("VennDiagram")
#install.packages("eulerr")
library("eulerr")
#install.packages("factoextra")
library("factoextra")
#install.packages("treemap")
library("treemap")
#install.packages("GOplot")
library("GOplot")
#install.packages("vegan")
library("vegan")
#install.packages("xlsx") 
#library("xlsx")
#install.packages("seqinr") 
library("seqinr")
#install.packages("openxlsx", dependencies = TRUE)
library(openxlsx)
library(data.table)
#install.packages("psych")
library("psych")

#if (!requireNamespace("BiocManager", quietly = TRUE))
#install.packages("BiocManager")
library("BiocManager")
#BiocManager::install("goseq")
library("goseq")
#BiocManager::install("GO.db")
library("GO.db")
#BiocManager::install("geneLenDataBase")
library("geneLenDataBase")
#BiocManager::install("qvalue")
library("qvalue")
#BiocManager::install("topGO")
library("topGO")


library(BiocManager)
library("Rgraphviz")
library("hgu95av2.db")

#install.packages("dcGOR")
library("dcGOR")
```

## 1.2. Load WGCNA - Data 

```{r}
# Cladocopium C1 annotation
#Func <- read.table("Annotation_C1_Genome.txt", sep="\t", h=T, quote = "", stringsAsFactors = FALSE, na.strings = c("", "NA"))
#head(Func)

# Separate KO and PFAM in Excel to have easier way to play with data
Func.SVD2SymGG5.1 <- read.table("Functions-WGCNA-Cladocopium-C1-Pocillopora-KO-PFAM-SVD2SymGG5-Final.txt", sep="\t", h=T, quote = "", stringsAsFactors = FALSE)
head(Func.SVD2SymGG5.1)
Func.SVD2SymGG5.2 <- Func.SVD2SymGG5.1[!is.na(Func.SVD2SymGG5.1$HeatMerge_moduleLabels),]
Func.SVD2SymGG5 <- Func.SVD2SymGG5.2[grep("Symb", Func.SVD2SymGG5.2$GeneID),]

# Separate KO and PFAM in Excel to have easier way to play with data
Func.SVD3SymGG3.1 <- read.table("Functions-WGCNA-Cladocopium-C1-Pocillopora-KO-PFAM-SVD3SymGG3-Final.txt", sep="\t", h=T, quote = "", stringsAsFactors = FALSE)
head(Func.SVD3SymGG3.1)
Func.SVD3SymGG3.2 <- Func.SVD3SymGG3.1[!is.na(Func.SVD3SymGG3.1$HeatMerge_moduleLabels),]
Func.SVD3SymGG3 <- Func.SVD3SymGG3.2[grep("Symb", Func.SVD3SymGG3.2$GeneID),]
```

## 1.3. Load All Genes Data

```{r}
mapC1 <- read.table("Fun-C1-Islands-Inside-Groups-Filtered-KO-PFAM-All.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE, quote = "")
head(mapC1)
```

# 2. PFAM enrichment

## 2.1. Function

```{r}
#WGCNA.Table <- Func.SVD2SymGG5
#DB <- MyPfam.total

PFAM.Fun.Enr <- function(DB, WGCNA.Table){
  myTabVF <- data.frame()
  for (i in 1:length(unique(WGCNA.Table$HeatMerge_moduleLabels))){
  
    myTab <- WGCNA.Table[grep(unique(WGCNA.Table$HeatMerge_moduleLabels)[i], WGCNA.Table$HeatMerge_moduleLabels),]
    MyPfam <- c(myTab$PFAM1[!is.na(myTab$PFAM1)], myTab$PFAM2[!is.na(myTab$PFAM2)],
                myTab$PFAM3[!is.na(myTab$PFAM3)], myTab$PFAM4[!is.na(myTab$PFAM4)],
                myTab$PFAM5[!is.na(myTab$PFAM5)], myTab$PFAM6[!is.na(myTab$PFAM6)],
                myTab$PFAM7[!is.na(myTab$PFAM7)], myTab$PFAM8[!is.na(myTab$PFAM8)],
                myTab$PFAM9[!is.na(myTab$PFAM9)], myTab$PFAM10[!is.na(myTab$PFAM10)])
    
    myTab.Bis <- unique(data.frame(GeneID = myTab$GeneID, PFAM1 = myTab$PFAM1))
    
    DB.Bis <- data.frame(All.PFAM = DB, Data = rep("All", length(DB)))
    DB.WGCNA <- data.frame(All.PFAM = MyPfam, Data = rep("WGCNA", length(MyPfam)))
    DB.All <- rbind(DB.Bis, DB.WGCNA)
    tab <- aggregate(DB.All$All.PFAM, by = list(Data = DB.All$Data, All.PFAM = DB.All$All.PFAM), length)
    
    DB.F <- data.frame(acast(tab, All.PFAM~Data, fill = 0, value.var = "x"))
    colnames(DB.F) <- c("Nb.Genes.In.Genome.With.PFAMX", "Nb.Genes.In.WGCNA.With.PFAMX")
    DB.F$Nb.Genes.In.WGCNA <- nrow(myTab.Bis) # Include Genes without PFAM
    DB.F$Nb.Genes.In.Genome <- nrow(mapC1.F) # Include Genes without PFAM
    DB.F$Nb.Genes.In.Genome.Without.PFAMX <- DB.F$Nb.Genes.In.Genome - DB.F$Nb.Genes.In.Genome.With.PFAMX
    DB.F$Nb.Genes.In.WGCNA.Without.PFAMX <- DB.F$Nb.Genes.In.WGCNA - DB.F$Nb.Genes.In.WGCNA.With.PFAMX
    
    myFisher <- data.frame()
    
    for(j in 1:nrow(DB.F)){
      x <- DB.F[j,c("Nb.Genes.In.WGCNA.With.PFAMX")]
      k <- DB.F[j,c("Nb.Genes.In.WGCNA")]
      m <- DB.F[j,c("Nb.Genes.In.Genome.With.PFAMX")]
      n <- DB.F[j,c("Nb.Genes.In.Genome.Without.PFAMX")]
      
      
      myMatrix <- t(matrix(c(x, m-x, m, k-x, n-(k-x), n, k, (m+n-k), m+n), ncol = 3))
      rownames(myMatrix) <- c(rownames(DB.F)[j], paste("!",rownames(DB.F)[j], sep =""), "Total")
      colnames(myMatrix) <- c(paste("WGCNA.", unique(WGCNA.Table$HeatMerge_moduleLabels)[i], sep =""), 
                              paste("!WGCNA.", unique(WGCNA.Table$HeatMerge_moduleLabels)[i], sep =""),
                              "Total")
      print(myMatrix)
      test <- fisher.test(myMatrix[1:2, 1:2], alternative = "two.sided")
      
      myRes <- cbind(x, k, m, n, test$p.value, test$estimate, rownames(DB.F)[j], unique(WGCNA.Table$HeatMerge_moduleLabels)[i])
      colnames(myRes) <- c("x", "k", "m", "n", "pvalue", "odds.ratio", "PFAM", "Module")
      myFisher <- rbind(myFisher, myRes)
    }
    myFisher$Samples <- rep(unique(Func.SVD2SymGG5$Samples), nrow(myFisher))
    myFisher.2 <- myFisher[myFisher$x != 0,]
    myFisher.2$padj <- p.adjust(myFisher.2$pvalue)
    write.table(myFisher.2, file = paste("PFAM-Fisher-WGCNA-C1-Islands-Inside-Groups-", unique(myTab$Samples), "-", unique(WGCNA.Table$HeatMerge_moduleLabels)[i],".txt", sep = ""), quote = FALSE, sep = "\t", row.names = FALSE)
    myTabVF <- rbind(myTabVF, myFisher.2)
  }
  myTabVF
}
```

## 2.2. Apply fucntion

```{r}
# Select Unique genes
# G5 / SVD2
mapC1.SVD2 <- mapC1[grep("SVD2", mapC1$Host.Pop),]
mapC1.G5 <- mapC1.SVD2[grep("G5", mapC1.SVD2$Cladocopium),]
mapC1.test <- data.frame(Gene.model = mapC1.G5$Gene.model, PFAM1 = mapC1.G5$PFAM1, PFAM2 = mapC1.G5$PFAM2, PFAM3 = mapC1.G5$PFAM3, 
                         PFAM4 = mapC1.G5$PFAM4, PFAM5 = mapC1.G5$PFAM5, PFAM6 = mapC1.G5$PFAM6, PFAM7 = mapC1.G5$PFAM7, PFAM8 = mapC1.G5$PFAM8, 
                         PFAM9 = mapC1.G5$PFAM9, PFAM10 = mapC1.G5$PFAM10)

mapC1.F <- unique(mapC1.test[order(mapC1.test$Gene.model),])
MyPfam.total <- c(as.character(mapC1.F$PFAM1), as.character(mapC1.F$PFAM2), as.character(mapC1.F$PFAM3), as.character(mapC1.F$PFAM4), as.character(mapC1.F$PFAM5), as.character(mapC1.F$PFAM6), as.character(mapC1.F$PFAM7), as.character(mapC1.F$PFAM8), as.character(mapC1.F$PFAM9), as.character(mapC1.F$PFAM10))

# SDV2G5
Pfam.Enrichment.SVD2SymGG5 <- PFAM.Fun.Enr(DB = MyPfam.total, WGCNA.Table = Func.SVD2SymGG5)
PFAM <- read.table("pfamA-New.txt", sep="\t", h=F, quote = "", stringsAsFactors = FALSE, na.strings = c("", "NA"))
colnames(PFAM) <- c("PFAM", "PFAM.Sum", "PFAM.Def")
Merge.PFAM1 <- merge(Pfam.Enrichment.SVD2SymGG5, PFAM, by="PFAM", all.x=T, sort = FALSE)
write.table(Merge.PFAM1, file = "PFAM-Fisher-WGCNA-C1-Islands-Inside-Groups-SVD2SymGG5.txt", quote = FALSE, sep = "\t", row.names = FALSE)

# G53/ SVD3
mapC1.SVD2 <- mapC1[grep("SVD3", mapC1$Host.Pop),]
mapC1.G5 <- mapC1.SVD2[grep("G3", mapC1.SVD2$Cladocopium),]
mapC1.test <- data.frame(Gene.model = mapC1.G5$Gene.model, PFAM1 = mapC1.G5$PFAM1, PFAM2 = mapC1.G5$PFAM2, PFAM3 = mapC1.G5$PFAM3, 
                         PFAM4 = mapC1.G5$PFAM4, PFAM5 = mapC1.G5$PFAM5, PFAM6 = mapC1.G5$PFAM6, PFAM7 = mapC1.G5$PFAM7, PFAM8 = mapC1.G5$PFAM8, 
                         PFAM9 = mapC1.G5$PFAM9, PFAM10 = mapC1.G5$PFAM10)

mapC1.F <- unique(mapC1.test[order(mapC1.test$Gene.model),])
MyPfam.total <- c(as.character(mapC1.F$PFAM1), as.character(mapC1.F$PFAM2), as.character(mapC1.F$PFAM3), as.character(mapC1.F$PFAM4), as.character(mapC1.F$PFAM5), as.character(mapC1.F$PFAM6), as.character(mapC1.F$PFAM7), as.character(mapC1.F$PFAM8), as.character(mapC1.F$PFAM9), as.character(mapC1.F$PFAM10))
# SDV3G3
Pfam.Enrichment.SVD3SymGG3 <- PFAM.Fun.Enr(DB = MyPfam.total, WGCNA.Table = Func.SVD3SymGG3)
PFAM <- read.table("pfamA-New.txt", sep="\t", h=F, quote = "", stringsAsFactors = FALSE, na.strings = c("", "NA"))
colnames(PFAM) <- c("PFAM", "PFAM.Sum", "PFAM.Def")
Merge.PFAM2 <- merge(Pfam.Enrichment.SVD3SymGG3, PFAM, by="PFAM", all.x=T, sort = FALSE)
write.table(Merge.PFAM2, file = "PFAM-Fisher-WGCNA-C1-Islands-Inside-Groups-SVD3SymGG3.txt", quote = FALSE, sep = "\t", row.names = FALSE)
```

# 3. PADJ

```{r}
Pfam.Enrichment.SVD2SymGG5 <- read.table("PFAM-Fisher-WGCNA-C1-Islands-Inside-Groups-SVD2SymGG5.txt", sep="\t", h=T, quote = "", stringsAsFactors = FALSE)
Pfam.Enrichment.SVD2SymGG5<-Pfam.Enrichment.SVD2SymGG5[order(Pfam.Enrichment.SVD2SymGG5$Module),]
padjust<-c()
for (i in unique(Pfam.Enrichment.SVD2SymGG5$Module)){padjust<-c(padjust,p.adjust(Pfam.Enrichment.SVD2SymGG5[Pfam.Enrichment.SVD2SymGG5$Module==i,6],method="BH"))}
Pfam.Enrichment.SVD2SymGG5$padj <- padjust
Pfam.Enrichment.SVD2SymGG5[order(Pfam.Enrichment.SVD2SymGG5$padj),][1:10,]
write.table(Pfam.Enrichment.SVD2SymGG5, file = "PFAM-Fisher-WGCNA-C1-Islands-Inside-Groups-SVD2SymGG5-New.txt", quote = FALSE, sep = "\t", row.names = FALSE)

Pfam.Enrichment.SVD3SymGG3 <- read.table("PFAM-Fisher-WGCNA-C1-Islands-Inside-Groups-SVD3SymGG3.txt", sep="\t", h=T, quote = "", stringsAsFactors = FALSE)
Pfam.Enrichment.SVD3SymGG3<-Pfam.Enrichment.SVD3SymGG3[order(Pfam.Enrichment.SVD3SymGG3$Module),]
padjust<-c()
for (i in unique(Pfam.Enrichment.SVD3SymGG3$Module)){padjust<-c(padjust,p.adjust(Pfam.Enrichment.SVD3SymGG3[Pfam.Enrichment.SVD3SymGG3$Module==i,6],method="BH"))}
Pfam.Enrichment.SVD3SymGG3$padj<-padjust
Pfam.Enrichment.SVD3SymGG3[order(Pfam.Enrichment.SVD3SymGG3$padj),][1:10,]
write.table(Pfam.Enrichment.SVD3SymGG3, file = "PFAM-Fisher-WGCNA-C1-Islands-Inside-Groups-SVD3SymGG3-New.txt", quote = FALSE, sep = "\t", row.names = FALSE)
```

# 4. Search Gene associated with padj & PFAM

```{r}
#WGCNA <- Func.SVD3SymGG3
#PFAM <- Pfam.Enrichment.SVD3SymGG3
#pval <- 0.01
#SVD <- "SVD3"
#Cladocopium <- "G3"
#Annot <- mapC1
#Genes.Association(WGCNA = Func.SVD3SymGG3, PFAM = Pfam.Enrichment.SVD3SymGG3, pval = 0.01, Annot = mapC1, Cladocopium = "G5", SVD = "SVD2")

Genes.Association <- function(WGCNA, PFAM, pval, Annot, Cladocopium, SVD){
  myRes <- data.frame()
  # Selection Cladocopium & SVD groups
  Annot1 <- Annot[grep(SVD, Annot$Host.Pop),]
  Annot.2 <- Annot1[grep(Cladocopium, Annot1$Cladocopium),]
  Annot.3 <- Annot.2[order(Annot.2$Gene.model),]
  Annot.select <- unique(Annot.3[,c("Gene.model", "UniProt.identifier..top.hit.and.or.top.hit.with.annotated.GO.", 
                             "Description.s..of.hit.s.", "E.value", "Gene.Ontology..GO..term", "PFAM1", "PFAM1.Sum", "PFAM1.Def", "PFAM2",
                             "PFAM2.Sum", "PFAM2.Def", "PFAM3", "PFAM3.Sum", "PFAM3.Def", "PFAM4", "PFAM4.Sum", "PFAM4.Def", "PFAM5", 
                             "PFAM5.Sum", "PFAM5.Def", "PFAM6",     "PFAM6.Sum", "PFAM6.Def", "PFAM7", "PFAM7.Sum", "PFAM7.Def", "PFAM8",
                             "PFAM8.Sum", "PFAM8.Def", "PFAM9", "PFAM9.Sum", "PFAM9.Def", "PFAM10",    "PFAM10.Sum", "PFAM10.Def", "KEGG1", 
                             "KEGG1.Def", "KEGG2", "KEGG2.Def")])
  
  # PFAM with pvalue adjusted
  PFAM.select <- PFAM[PFAM$padj <= pval,]
  
  for (i in 1:length(unique(PFAM.select$Module))){
    # Select genes associated to module of interest
    WGCNA.select <- WGCNA[grep(unique(PFAM.select$Module)[i], WGCNA$HeatMerge_moduleLabels),]
    MyGenes <- WGCNA.select$Gene.model
    
    myNewAnnot <- data.frame()
    # Recherche des gènes associées dans le module
    for(j in 1:length(MyGenes)){
      myNewAnnot <- rbind(myNewAnnot, Annot.select[which(Annot.select$Gene.model == MyGenes[j]),])
    }
    myNewAnnot$PFAM.tot <- paste(myNewAnnot$PFAM1, myNewAnnot$PFAM2, myNewAnnot$PFAM3, myNewAnnot$PFAM4, myNewAnnot$PFAM5,
                                 myNewAnnot$PFAM6, myNewAnnot$PFAM7, myNewAnnot$PFAM8, myNewAnnot$PFAM9, myNewAnnot$PFAM10, 
                                 sep = ";")
    
    # Recherche des PFAM assiciés à ces gènes dans le module
    myPFAM <- PFAM.select[grep(unique(PFAM.select$Module)[i], PFAM.select$Module),]
    myData <- data.frame()
    
    myTemp <- data.frame()
    for (k in 1:length(unique(myPFAM$PFAM))){
      myTemp <- myNewAnnot[grep(unique(myPFAM$PFAM)[k], myNewAnnot$PFAM.tot),]
      myTemp$PFAM.Search <- rep(unique(myPFAM$PFAM)[k], nrow(myTemp))
      myData <- rbind(myData, myTemp)
    }
    myData$Module <- rep(unique(PFAM.select$Module)[i], nrow(myData))
    write.table(myData, file = paste("Genes-Associated-PFAM-",Cladocopium, SVD,"Module", unique(PFAM.select$Module)[i], "WGCNA.txt", sep = "-"), quote = FALSE, sep = "\t", row.names = FALSE)
    myRes <- rbind(myRes, myData)
  }
  myRes
}

Pfam.SVD2SymGG5.Genes <- Genes.Association(WGCNA = Func.SVD2SymGG5, PFAM = Pfam.Enrichment.SVD2SymGG5, pval = 0.01, Annot = mapC1, Cladocopium = "G5", SVD = "SVD2")
write.table(Pfam.SVD2SymGG5.Genes, file = "Genes-Associated-PFAM-SVD2SymGG5-All-Modules-WGCNA.txt", quote = FALSE, sep = "\t", row.names = FALSE)

Pfam.SVD3SymGG3.Genes <- Genes.Association(WGCNA = Func.SVD3SymGG3, PFAM = Pfam.Enrichment.SVD3SymGG3, pval = 0.01, Annot = mapC1, Cladocopium = "G3", SVD = "SVD3")
write.table(Pfam.SVD3SymGG3.Genes, file = "Genes-Associated-PFAM-SVD3SymGG3-All-Modules-WGCNA.txt", quote = FALSE, sep = "\t", row.names = FALSE)
```

